### ISSUE TITLE
Add support for RGBA

### ISSUE THREAD

**Issue by Olie-Chanz** [optimistdigital/nova-color-field#2]
It would be nice to add support for RGBA.
![image](https://user-images.githubusercontent.com/78068318/122497722-711a1e00-d020-11eb-96f3-6b43c977d166.png)

**Comment by Tarpsvo** [comment]
Hi! Version 1.1.0 added two new features:  `->displayAs()` and `->saveAs()`. You can now `->displayAs('rgba')` and `->saveAs('rgba')` to both show and save the field as RGBA.

PS: it's recommended to cast the field to array when saving as RGBA or HSL.
