### ISSUE TITLE
Latest version breaks nova

### ISSUE THREAD

**Issue by martin-ro** [optimistdigital/nova-color-field#3]
Hi, 

after updating to 1.1 I see an error `TypeError: t is undefined` and the field stops working.

Any idea what that could be?

**Comment by Tarpsvo** [comment]
Hi! In what view is this?

**Comment by Tarpsvo** [comment]
I also just released version 1.1.1. Can you check if that fixed the crash? Thanks!

**Comment by StanBarrows** [comment]
I can confirm it currently works on v3.30.0
