### ISSUE TITLE
Without 

### ISSUE THREAD

**Issue by StanBarrows** [optimistdigital/nova-color-field#6]
Hey @Tarpsvo 

Great work you did with this colour picker!

Is there currently an option to hide the suggestions completely? I want to use it as a manual input field showing the colours after saving the form.

Best regards
Sebastian

<img width="338" alt="grafik" src="https://user-images.githubusercontent.com/10268813/141295350-8637b4d3-bde0-40d2-aea4-4bf6b0c8cbe0.png">

**Comment by Tarpsvo** [comment]
Heya! I added a new `->hidePicker()` option for your usecase. ;) Release in version 1.2.0. Good luck!

**Comment by StanBarrows** [comment]
You're awesome! Thanks a lot
